### ISSUE TITLE
Firefox patch version

### ISSUE THREAD

**Issue by Alex-Sokolov** [wilddeer/Sniffer#9]
Have installed Firefox 45.0.2, but demo-page show
`Sniff.browser.version: 45.0`

**Comment by wilddeer** [comment]
Cause UA string says it’s 45.0:
`Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0`

¯\\\_(ツ)\_/¯
